const state={tab:'suspects',found:new Set(),visited:new Set(),location:'hall',dialogue:null};
const $=s=>document.querySelector(s);
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const screen=$('#'+id);if(screen)screen.classList.add('active')}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2200)}
function getLocation(id){return CASE001.locations.find(x=>x.id===id)}
function renderLocations(){const nav=$('#locationNav');nav.innerHTML=CASE001.locations.map(l=>`<button class="location-btn ${l.id===state.location?'active':''}" data-location="${l.id}"><span>${l.icon}</span><span>${l.name}</span>${state.visited.has(l.id)?'<b>✓</b>':''}</button>`).join('');nav.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>goTo(b.dataset.location))}
function goTo(id){const l=getLocation(id);if(!l)return;state.location=id;state.visited.add(id);renderScene();renderLocations();window.scrollTo({top:0,behavior:'smooth'})}
function renderScene(){const l=getLocation(state.location);const scene=$('#scene');scene.style.backgroundImage=`linear-gradient(180deg,rgba(5,8,15,.12),rgba(5,8,15,.78)),url('${l.bg}')`;$('sceneLabel').textContent=`ЛОКАЦИЯ • ${l.icon}`;$('sceneTitle').textContent=l.name;$('sceneDescription').textContent=l.description;$('#hotspots').innerHTML=l.hotspots.map(h=>`<button class="hotspot ${h.type}" data-hotspot="${h.id}"><span>${h.icon}</span>${h.name}${h.evidence&&state.found.has(h.evidence)?'<i>✓</i>':''}</button>`).join('');$('#hotspots').querySelectorAll('[data-hotspot]').forEach(b=>b.onclick=()=>useHotspot(l.hotspots.find(h=>h.id===b.dataset.hotspot)));renderEvidenceCount()}
function useHotspot(h){if(!h)return;if(h.type==='travel'){goTo(h.target);return}if(h.type==='evidence'){if(!state.found.has(h.evidence)){state.found.add(h.evidence);toast('Новая улика добавлена в дело');renderEvidence();renderScene()}else toast('Ты уже изучил этот объект');return}if(h.type==='dialogue'){openDialogue(h.name,h.dialogue);return}toast(h.text||'Ничего подозрительного не найдено.')}
function openDialogue(title,lines){state.dialogue={title,lines,index:0};renderDialogue()}
function renderDialogue(){const d=$('#dialogue');if(!state.dialogue){d.classList.add('hidden');return}d.classList.remove('hidden');const x=state.dialogue;d.innerHTML=`<div class="dialogue-head"><strong>${x.title}</strong><button id="closeDialogue">×</button></div><div class="dialogue-text">«${x.lines[x.index]}»</div><button class="primary dialogue-next" id="nextDialogue">${x.index<x.lines.length-1?'Дальше':'Закончить разговор'}</button>`;$('#closeDialogue').onclick=()=>{state.dialogue=null;renderDialogue()};$('#nextDialogue').onclick=()=>{if(x.index<x.lines.length-1){x.index++;renderDialogue()}else{state.dialogue=null;renderDialogue();toast('Разговор завершён')}}}
function renderEvidenceCount(){$('#evidenceCount').textContent=state.found.size;$('#evidenceTotal').textContent=CASE001.evidence.length}
function renderSuspects(){$('#tab-suspects').innerHTML=`<div class="cards">${CASE001.suspects.map(s=>`<article class="card"><div class="person"><div class="avatar">${s.icon}</div><div><h3>${s.name}</h3><p>${s.role}</p><span class="tag">Показания</span><p class="statement">«${s.statement}»</p><details><summary>Личная тайна</summary><p>${s.secret}</p></details></div></div></article>`).join('')}</div>`}
function renderEvidence(){$('#tab-evidence').innerHTML=`<div class="cards">${CASE001.evidence.map(e=>{const found=state.found.has(e.id);return `<article class="card evidence ${found?'found':''}"><div class="icon">${found?e.icon:'❓'}</div><div><strong>${found?e.title:'Неизвестная улика'}</strong><p>${found?e.text:'Исследуй локации, чтобы обнаружить этот факт.'}</p></div></article>`}).join('')}</div>`;renderEvidenceCount()}
function renderTimeline(){$('#tab-timeline').innerHTML=`<div class="panel timeline-panel"><div class="timeline">${CASE001.timeline.map(e=>`<div class="event"><div class="time">${e[0]}</div><div>${e[1]}</div></div>`).join('')}</div></div>`}
function renderTheory(){$('#tab-theory').innerHTML=`<div class="theory-note panel"><b>Теория преступления</b><span>Недостаточно назвать убийцу. Нужно восстановить всю цепочку.</span></div><div class="theory-grid"><div class="field"><label>КТО УБИЙЦА?</label><select id="killer"><option value="">Выберите</option>${CASE001.suspects.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></div><div class="field"><label>МОТИВ</label><select id="motive"><option value="">Выберите</option><option value="romance">Тайные отношения</option><option value="money">Деньги</option><option value="blackmail">Шантаж</option><option value="revenge">Месть</option></select></div><div class="field"><label>ОРУЖИЕ</label><select id="weapon"><option value="">Выберите</option><option value="knife">Нож</option><option value="gun">Пистолет</option><option value="poison">Яд</option></select></div><div class="field"><label>МЕСТО</label><select id="place"><option value="">Выберите</option><option value="office">Кабинет</option><option value="kitchen">Кухня</option><option value="garden">Сад</option></select></div><div class="field"><label>ВРЕМЯ</label><select id="time"><option value="">Выберите</option><option value="20:53">20:53</option><option value="21:04">21:04</option><option value="21:15">21:15</option></select></div><div class="field"><label>КАК СКРЫЛИ?</label><select id="method"><option value="">Выберите</option><option value="camera">Отключили камеру</option><option value="window">Сымитировали взлом окна</option><option value="fire">Устроили пожар</option></select></div></div><button class="primary" id="solve">Восстановить события</button>`;$('#solve').onclick=solve}
function solve(){const a=CASE001.answer;const ids=['killer','motive','weapon','place','time','method'];if(ids.some(id=>!$('#'+id).value)){toast('Заполни всю теорию преступления');return}const score=ids.reduce((n,id)=>n+($('#'+id).value===a[id]?1:0),0);showScreen('result');$('#resultBox').innerHTML=score===6?`<div class="eyebrow">ДЕЛО РАСКРЫТО</div><h2 class="correct">Блестящая работа.</h2><p>Анна Морозова заманила Артёма в кабинет, воспользовалась отключением камеры и убила его ножом. Тайные отношения стали мотивом.</p><p><b>6 / 6</b> элементов восстановлены.</p><div class="case-summary"><span>✓ Убийца установлена</span><span>✓ Мотив найден</span><span>✓ Время подтверждено</span><span>✓ Способ сокрытия найден</span></div>`:`<div class="eyebrow">РАССЛЕДОВАНИЕ НЕ ЗАВЕРШЕНО</div><h2 class="wrong">Версия содержит ошибки.</h2><p>Правильность версии: <b>${score} / 6</b>. Проверь улики и не путай чужую тайну с доказательством убийства.</p><button class="secondary" id="backInvestigation">Вернуться к расследованию</button>`;const back=$('#backInvestigation');if(back)back.onclick=()=>showScreen('investigation')}
function setTab(tab){state.tab=tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.tab-content').forEach(x=>x.classList.add('hidden'));$('#tab-'+tab).classList.remove('hidden')}
function init(){if(typeof CASE001==='undefined'){console.error('CASE001 не загружен');return}renderSuspects();renderEvidence();renderTimeline();renderTheory();$('#introText').textContent=CASE001.intro;renderLocations();state.visited.add('hall');renderScene();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));const start=$('[data-action="start"]');if(start){start.addEventListener('click',e=>{e.preventDefault();showScreen('investigation');window.scrollTo({top:0,behavior:'smooth'})})}const restart=$('[data-action="restart"]');if(restart)restart.addEventListener('click',()=>showScreen('investigation'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
