const state={tab:'suspects',found:new Set()};
const $=s=>document.querySelector(s);
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function renderSuspects(){ $('#tab-suspects').innerHTML=`<div class="cards">${CASE001.suspects.map(s=>`<article class="card"><div class="person"><div class="avatar">${s.icon}</div><div><h3>${s.name}</h3><p>${s.role}</p><span class="tag">Показания</span><p style="margin-top:10px">«${s.statement}»</p><details style="margin-top:12px"><summary>Личная тайна</summary><p style="margin-top:8px">${s.secret}</p></details></div></div></article>`).join('')}</div>`}
function renderEvidence(){$('#tab-evidence').innerHTML=`<div class="cards">${CASE001.evidence.map((e,i)=>`<article class="card evidence"><div class="icon">${e.icon}</div><div><strong>${e.title}</strong><p>${e.text}</p></div></article>`).join('')}</div>`}
function renderTimeline(){$('#tab-timeline').innerHTML=`<div class="panel" style="padding:22px"><div class="timeline">${CASE001.timeline.map(e=>`<div class="event"><div class="time">${e[0]}</div><div>${e[1]}</div></div>`).join('')}</div></div>`}
function renderTheory(){$('#tab-theory').innerHTML=`<div class="theory-grid"><div class="field"><label>КТО УБИЙЦА?</label><select id="killer"><option value="">Выберите</option>${CASE001.suspects.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></div><div class="field"><label>МОТИВ</label><select id="motive"><option value="">Выберите</option><option value="romance">Тайные отношения</option><option value="money">Деньги</option><option value="blackmail">Шантаж</option><option value="revenge">Месть</option></select></div><div class="field"><label>ОРУЖИЕ</label><select id="weapon"><option value="">Выберите</option><option value="knife">Нож</option><option value="gun">Пистолет</option><option value="poison">Яд</option></select></div><div class="field"><label>МЕСТО</label><select id="place"><option value="">Выберите</option><option value="office">Кабинет</option><option value="kitchen">Кухня</option><option value="garden">Сад</option></select></div><div class="field"><label>ВРЕМЯ</label><select id="time"><option value="">Выберите</option><option value="20:53">20:53</option><option value="21:04">21:04</option><option value="21:15">21:15</option></select></div><div class="field"><label>КАК СКРЫЛИ ПРЕСТУПЛЕНИЕ?</label><select id="method"><option value="">Выберите</option><option value="camera">Отключили камеру</option><option value="window">Сымитировали взлом окна</option><option value="fire">Устроили пожар</option></select></div></div><button class="primary" id="solve">Восстановить события</button>`;$('#solve').onclick=solve}
function solve(){const a=CASE001.answer;const ids=['killer','motive','weapon','place','time','method'];const missing=ids.some(id=>!$('#'+id).value);if(missing){toast('Заполни всю теорию преступления');return}const score=ids.reduce((n,id)=>n+($('#'+id).value===a[id]?1:0),0);showScreen('result');$('#resultBox').innerHTML=score===ids.length?`<div class="eyebrow">ДЕЛО РАСКРЫТО</div><h2 class="correct">Блестящая работа.</h2><p>Анна Морозова убила Артёма во время встречи в кабинете, а отключение камеры создало окно для сокрытия преступления. Ты восстановил всю цепочку.</p><p><b>6 / 6</b> правильных элементов.</p>`:`<div class="eyebrow">РАССЛЕДОВАНИЕ НЕ ЗАВЕРШЕНО</div><h2 class="wrong">Версия содержит ошибки.</h2><p>Правильность версии: <b>${score} / 6</b>. Некоторые тайны персонажей ещё не означают, что они убийцы. Вернись к делу и проверь факты.</p>`}
function init(){renderSuspects();renderEvidence();renderTimeline();renderTheory();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab-content').forEach(x=>x.classList.add('hidden'));$('#tab-'+b.dataset.tab).classList.remove('hidden')});document.querySelector('[data-action=start]').onclick=()=>showScreen('investigation');document.querySelector('[data-action=restart]').onclick=()=>showScreen('investigation')}
init();